//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhap
    {
        public int FK_iMahoadonnhapID { get; set; }
        public int FK_iMathangID { get; set; }
        public int iSoluong { get; set; }
        public decimal dGianhap { get; set; }
    
        public virtual HoaDonNhap HoaDonNhap { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
