//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHang
    {
        public LoaiHang()
        {
            this.MatHang = new HashSet<MatHang>();
        }
    
        public int PK_iMaloaihangID { get; set; }
        public string sTenloaihang { get; set; }
    
        public virtual ICollection<MatHang> MatHang { get; set; }
    }
}
