//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.HoaDonNhap = new HashSet<HoaDonNhap>();
        }
    
        public int PK_iManhacungcapID { get; set; }
        public string sTennhacungcap { get; set; }
        public string sSDT { get; set; }
        public string sDiachi { get; set; }
    
        public virtual ICollection<HoaDonNhap> HoaDonNhap { get; set; }
    }
}
