//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.HoaDonBan = new HashSet<HoaDonBan>();
            this.HoaDonNhap = new HashSet<HoaDonNhap>();
        }
    
        public int PK_iManhanvienID { get; set; }
        public string sHoten { get; set; }
        public Nullable<System.DateTime> dNgaysinh { get; set; }
        public Nullable<bool> bGioitinh { get; set; }
        public string sSDT { get; set; }
        public string sEmail { get; set; }
        public string sDiachi { get; set; }
        public string sUser { get; set; }
        public string sPass { get; set; }
        public bool bQuyen { get; set; }
        public Nullable<int> fkRole { get; set; }
    
        public virtual ICollection<HoaDonBan> HoaDonBan { get; set; }
        public virtual ICollection<HoaDonNhap> HoaDonNhap { get; set; }
        public virtual Role Role { get; set; }
    }
}
