//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.NhanVien = new HashSet<NhanVien>();
        }
    
        public int PK_iRoleID { get; set; }
        public string sTen { get; set; }
    
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}
